### ISSUE TITLE
Partitions with path defined, but not formated should be displayed properly

### ISSUE THREAD

**Issue by radare** [voidlinux/void-installer#1]
In the installer if you select some partitions (rootfs) to format, but others to not format (/home), when entering the "install" menu, it warns you that ALL partitions will be formatted, which is not true, because it only formats the ones you have preselected.

**Comment by icemodding** [comment]
Same problem here. Any fix?

**Comment by Vaelatern** [comment]
You need to make an issue against the correct repo: voidlinux/void-mklive
