### ISSUE TITLE
filed to install grub on dev/sda!

### ISSUE THREAD

**Issue by VadimGit** [voidlinux/void-installer#10]
Wanted to play with musl based void but got this error.
Is it bug ? Or I did something wrong.
Can I use syslinux instead of grub?

**Comment by Duncaen** [comment]
You did something wrong, without logs/errors nobody can help you.
`syslinux` can be used but there are iirc. there are no update hooks and you would have to update/create the config yourself.

**Comment by VadimGit** [comment]
```bash
warning: this GPT partition label contains no BIOS Boot Partition.
```
Sorry my mistake.
