### ISSUE TITLE
remove anon from /etc/sudoers

### ISSUE THREAD

**Issue by grafoo** [voidlinux/void-installer#14]
when using the **Local (Packages from ISO image)** installation source, `/etc/sudoers` will be copied over to the resulting installation filesystem which includes the line `anon ALL=(ALL) NOPASSWD: ALL`. Though there's actually no such user in the newly created system, adding this account in the future will lead to serious security implication when the person of doing so is unaware of anon's sudo privileges.

**Comment by Duncaen** [comment]
The current installer is part of this repository https://github.com/voidlinux/void-mklive

**Comment by grafoo** [comment]
opened issue [https://github.com/voidlinux/void-mklive/issues/76](https://github.com/voidlinux/void-mklive/issues/76)
