### ISSUE TITLE
support wifi networks with longer password

### ISSUE THREAD

**Issue by revington** [voidlinux/void-installer#15]
WPA2 supports passwords with length up to 63. The install did not allow me to introduce my full password.

**Comment by Vaelatern** [comment]
Did you do this on a live-cd? Or did you actually use this script?

Your issue may be better placed at https://github.com/voidlinux/void-mklive if you used a live cd.

**Comment by revington** [comment]
Well, I created my own iso file with the void-mklive because I use a weird keyboard layout and then I installed the system with this script.
The password field, defined on [the ncurses form](https://github.com/voidlinux/void-installer/blob/master/applets/02-network-wifi.sh) dit not allow me to write the full password.

**Comment by Duncaen** [comment]
No, this repository is obsolete, the installer script on the ISOs is in https://github.com/voidlinux/void-mklive `installer.sh.in`.

**Comment by revington** [comment]
aha! you are right
