### ISSUE TITLE
All non-free firmware should be enabled by the user

### ISSUE THREAD

**Issue by greencopper** [voidlinux/void-installer#18]
Hi,

It has come to my attention that Void Linux installs non-free firmware without letting the user know about it.

https://forum.voidlinux.eu/t/unacceptable-nvidia-binary-blob-in-base-install/

Even though it can be argued that you cannot avoid non-free firmware completely in any hardware, I believe we should make it so a user explicitly needs to enable this before it's run.

It's not because non-free is avoided by this, it clearly isn't as it's already located on most ROMS, but it's so the user knows everything about what gets installed and he actually has a choice to avoid it.

During installation of Debian, if the installer detects hardware that requires some non-free binary firmware, the user is asked if he want to provide the non-free blob. Or he can choose to run the "netinst" version with non-free firmware.

Could we not make it so the user is asked in Void Linux?

**Comment by Duncaen** [comment]
It never runs on your CPU and it doesn't get touched at all if its not needed for you hardware.
And they have a "free" license, just not the RMS free.

Btw. this is the wrong repository, the installer is part of https://github.com/voidlinux/void-mklive and issues should go there.

**Comment by greencopper** [comment]
> Btw. this is the wrong repository.

Ups, sorry, my bad!
