### ISSUE TITLE
Keymap list is alphabetically ordered.  Common keymaps (eg US) should be first.

### ISSUE THREAD

**Issue by Veyrdite** [voidlinux/void-installer#19]
Source: latest live isos, 20160420

**Comment by Duncaen** [comment]
This isn't worth it, the menu is created by listing available files, reordering them just adds complexity and is discriminating.
https://github.com/voidlinux/void-mklive/blob/master/installer.sh.in#L494
And wrong repository, https://github.com/voidlinux/void-mklive contains the current installer.
