### ISSUE TITLE
Locale selection step does not work

### ISSUE THREAD

**Issue by Veyrdite** [voidlinux/void-installer#20]
Source: latest live isos, 20160420

Error message briefly flashes behind 'dialog':

    grep: /etc/default/libc-locales: No such file or directory

**Comment by Duncaen** [comment]
Wrong repository, https://github.com/voidlinux/void-mklive contains the current installer.
Anyways this is not an issues, musl doesn't support locales. (assuming you used a musl iso)

**Comment by Veyrdite** [comment]
Ah thankyou, this must have been the issue.  I tried a couple of isos, but they were both musl variants.

Sorry for the bother.
