### ISSUE TITLE
Error when trying to login to base installer image

### ISSUE THREAD

**Issue by alaskan-hippie** [voidlinux/void-installer#21]
I have downloaded, verified, and copied (with `dd`) to USB drive the following void-live image:  

`void-live-x86_64-20160420.iso                      20-Apr-2016 14:36           258998272`

Upon booting this image, I'm presented with the login screen as expected, however when attempting to login I receive an error:  

`Error in service module`

... and then the "Welcome to Void Linux Live system" message appears with a new login prompt.

I can't pull any logs since I can't log in, so this is all the information I have. If you need anything else let me know.

***Edit: Confirmed to be doing the same thing on the xfce live installer image.

**Comment by jcjordyn130** [comment]
That error comes from PAM.

**Comment by Vaelatern** [comment]
Have you tried on newer images?

**Comment by alaskan-hippie** [comment]
Apologies for super late reply. 

The image released after this issue was started had corrected the problem (I forget exactly when). 

As this was resolved, I'm closing this out
