### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by jradix** [voidlinux/void-installer#22]
Hello,
I know you have plenty of things to work on, but it would be nice to have an unattended installation system like you have on Ubuntu/Debian or BSD systems. It would be easier to create boxes and images for virtualization systems and for Vagrant/Packer.

**Comment by Duncaen** [comment]
This repository is obsolete, `void-mklive` contains the installer, there is already a pull request for a advanced unattended installation script https://github.com/voidlinux/void-mklive/pull/73.
And there are already scripts to create images `mkimage.sh`, `mkrootfs.sh` and `mklive.sh` for ISOs.
