### ISSUE TITLE
RFC: Rename this repo to point out it is obsolete

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-installer#23]

**Comment by wezm** [comment]
Where is the successor?

**Comment by the-maldridge** [comment]
This *IS* the successor.  The live version is a single file within voidlinux/void-mklive .

**Comment by pepa65** [comment]
THIS is the successor doesn't make sense, as this repo hasn't been updated for a year. It seems the successor is build in https://github.com/voidlinux/void-mklive, the `installer.sh` script.

**Comment by the-maldridge** [comment]
Given that I am the primary current maintainer for the repository you linked, I'll stand by my previous answer.  This is the successor to the version that is currently live, but it isn't ready yet.  Its not dead, its not obsolete, it just isn't ready yet.

**Comment by pepa65** [comment]
Sorry, I was just trying to make sense of what you said. There is no visible sign of development in this repo, there is not even any other branch.

So what is this referring to??

> The live version is a single file within voidlinux/void-mklive

**Comment by the-maldridge** [comment]
The current version is in the void-mklive repository of the voidlinux organization.  It is a single file called "installer.sh".  This is supposed to some day replace it but that is going to be a long way off if ever.
