### ISSUE TITLE
No way to convert to GPT from MBR

### ISSUE THREAD

**Issue by soundsofthem** [voidlinux/void-installer#24]
I don't know anything about computers, I could be wrong but this is an issue for me.

**Comment by Gottox** [comment]
https://askubuntu.com/questions/84501/how-can-i-change-convert-a-ubuntu-mbr-drive-to-a-gpt-and-make-ubuntu-boot-from - true for void too

**Comment by soundsofthem** [comment]
I couldn't find a way to execute any of the utilities they list in that askubuntu link from the image available on the void website

**Comment by soundsofthem** [comment]
please reopen

**Comment by Gottox** [comment]
This is a place for reporting bugs - like errors in software we wrote - , not for user support. Please consider the [forum](https://forum.voidlinux.eu) or IRC.

**Comment by soundsofthem** [comment]
it bugged me

**Comment by soundsofthem** [comment]
also I'm 90% certain it says "Issues" not "Bugs"

**Comment by Gottox** [comment]
Please consider the forum or IRC instead.
