### ISSUE TITLE
Hi, I couldn't install Void because I couldn't switch my partition table to GPT with the software I was provided access to by void-installer

### ISSUE THREAD

**Issue by soundsofthem** [voidlinux/void-installer#25]
here's some reasons why this is easily fixable and really pressing:

there's tools a number of tools with pretty similar functionality to the one provided but which also are capable of doing this conversion
The user was deterred from installing Void
The user is losing faith in Linux distributions' ability to do basic shit that someone else had already addressed before they decided to come along and repackage everything and slap their sticker on it

**Comment by soundsofthem** [comment]
FUCK ME THEY CALL GDISK FDISK? PS WHY CAN'T I CHANGE THE SHIT FROM CFDISK

**Comment by soundsofthem** [comment]
I would delete this but there isn't a button to do that
I also accidently forked your repo because I wanted to see the 8 other forks and it
looked
like one button, rather than 2 that got thrown together
https://a.pomf.cat/mzskkf.png

**Comment by soundsofthem** [comment]
likewise, I would delete my own fork but I needed to do a confirmation by typing the name of the repo (easy enough) and then type my own password (I've forgotten it already)

**Comment by Duncaen** [comment]
Changing the partition type is nothing trivial without formating the disk, this is something that can go wrong.
The easiest way is to use `wipefs` to delete the signature and all data and then use `cfdisk` to create a new partition table.

**Comment by soundsofthem** [comment]
you can convert mbr to gpt without data loss according to some people (it looked like a hack, honestly)
thank you so much Duncaen, this is actually what I needed

**Comment by Gottox** [comment]
Guy, you're really not making friends atm.
