### ISSUE TITLE
installer has no option of keeping files (not formatting) /home partition?!

### ISSUE THREAD

**Issue by zyllion** [voidlinux/void-installer#26]
as the title says. i use a multi boot setup with same /home partition among different distros so it would be a pain to format all that just to add void into the mix :)
  
*found a solution ( which is none ) xD the warning in red actually isn't true , while creating the filesystem the installer doesnt erase /home its just mounting it. -_- misleading text the only concern.

**Comment by pullmoll** [comment]
First this is the wrong repo. void-installer is part of https://github.com/voidlinux/void-mklive

Second after selecting a partition's mount point void-installer asks you whether or not you want to format that partition.

I did a similar thing you want to do in a recent setup of a second Void (x86_64-musl) on two more extended partitions on the same drive where my Void x86_64 lives, sharing /home between them.
