### ISSUE TITLE
WiFi setup fails with "ERROR: DHCP request failed for wlp2s0. Check /dev/tty8 for errors."

### ISSUE THREAD

**Issue by almgru** [voidlinux/void-installer#27]
Every time I've installed Void and try to setup a wireless configuration through the void-installer menu, I get the message `ERROR: DHCP request failed for wlp2s0. Check /dev/tty8 for errors.`.

tty8 only displays 
```
sending commands to master dhcpcd process
```

I solved it by exiting the installer, restarting dhcpcd with `sudo sv restart dhcpcd` and then reopening the installer. Maybe this is a step the installer could take after configuring the network? 

Setup:
Void image: void-live-x86_64-20171007
Firmware: UEFI
Computer model: Dell Latitude E4630 (also reproduced on Toshiba Satellite L500-12E)
Wifi card: Intel Centrino Ultimate-N 6300

**Comment by dwitterer** [comment]
Can confirm. Same image on Dell Inspiron 15 EUFI.

**Comment by the-maldridge** [comment]
This repo is for an installer that's not in use on a project that's not monitored anymore.  If your issue persists, please reopen it on https://github.com/void-linux/void-mklive/issues
