### ISSUE TITLE
Installer should offer user creation

### ISSUE THREAD

**Issue by archusr** [voidlinux/void-installer#9]
Logging in via default graphical login after install fails, presumably due to missing non-root user required for Xorg.

**Comment by go2null** [comment]
The offer is included in ` void-live-x86_64-musl-20170220-xfce.iso` (and possibly before) and is documented in the [wiki](https://wiki.voidlinux.eu/Installation#UserAccount).

However, the user account is **_not_** created.

**Comment by Vaelatern** [comment]
voidlinux/void-mklive

**Comment by the-maldridge** [comment]
Also the installer does create that user in the media I just tested.  If you wish to file an issue against the correct repo we can troubleshoot there.
